/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import Classes.Aluno;
import MySQL.AlunoDAO;
import MySql.DataSource;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;

/**
 *
 * @author Marcos
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    DataSource dataSource = new DataSource();
    AlunoDAO alunoDao = new AlunoDAO(dataSource);
    Aluno aluno = new Aluno();

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botaoCreate = new javax.swing.JButton();
        botaoDelete = new javax.swing.JButton();
        botaoUpdate = new javax.swing.JButton();
        botaoExit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        botaoDetalhe = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaAlunos = new javax.swing.JTable();
        botaoRead = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciador de Academia");
        setMinimumSize(new java.awt.Dimension(870, 502));
        setSize(new java.awt.Dimension(0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setOpaque(false);

        botaoCreate.setText("Criar");
        botaoCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCreateActionPerformed(evt);
            }
        });

        botaoDelete.setText("Deletar");
        botaoDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDeleteActionPerformed(evt);
            }
        });

        botaoUpdate.setText("Alterar");
        botaoUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoUpdateActionPerformed(evt);
            }
        });

        botaoExit.setText("Sair");
        botaoExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExitActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botaoDetalhe.setText("Detalhes");
        botaoDetalhe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDetalheActionPerformed(evt);
            }
        });

        tabelaAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Cpf", "Nome", "DataNascimento", "Telefone", "Email", "Endereço"
            }
        ));
        jScrollPane2.setViewportView(tabelaAlunos);

        botaoRead.setText("Atualizar");
        botaoRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoReadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
                .addGap(88, 88, 88))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap(709, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(botaoRead)
                        .addComponent(botaoDetalhe))
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(botaoRead)
                    .addGap(18, 18, 18)
                    .addComponent(botaoDetalhe)
                    .addContainerGap(232, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botaoCreate)
                        .addGap(18, 18, 18)
                        .addComponent(botaoUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(botaoDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoExit))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCreate)
                    .addComponent(botaoUpdate)
                    .addComponent(botaoDelete)
                    .addComponent(botaoExit))
                .addGap(72, 72, 72))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 870, 500);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagemdefundo/Design sem nome 2.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setMaximumSize(new java.awt.Dimension(854, 480));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1121, 1920);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
    }//GEN-LAST:event_formWindowOpened

    private void botaoReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoReadActionPerformed
        read();
        
    }//GEN-LAST:event_botaoReadActionPerformed

    private void botaoCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCreateActionPerformed

        TelaCadastro telaCadastro = new TelaCadastro();
        telaCadastro.setVisible(true);
    }//GEN-LAST:event_botaoCreateActionPerformed

    private void botaoDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDeleteActionPerformed
        // TODO add your handling code here:
        String alunoDeletado = selecionarAluno();
        if (alunoDeletado != null){
            delete(alunoDeletado);
        }
    }//GEN-LAST:event_botaoDeleteActionPerformed

    private void botaoUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoUpdateActionPerformed
        // TODO add your handling code here:
        String alunoAlterado = selecionarAluno();
        if (alunoAlterado != null){
            TelaEditar telaEditar = new TelaEditar();
            telaEditar.inicializarCampos(alunoAlterado);
            telaEditar.setVisible(true);
        }
    }//GEN-LAST:event_botaoUpdateActionPerformed

    private void botaoExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_botaoExitActionPerformed

    private void botaoDetalheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDetalheActionPerformed
        // TODO add your handling code here:
        
        if (tabelaAlunos.getSelectedRowCount() != 0){
            
            mostrarDetalhes();
        }
        else{
            JOptionPane.showMessageDialog(null, "Selecione um aluno primeiro.");
        }
        
    }//GEN-LAST:event_botaoDetalheActionPerformed

    private void mostrarDetalhes(){
        DefaultTableModel modelo = (DefaultTableModel)tabelaAlunos.getModel();
        int linha = tabelaAlunos.getSelectedRow();
        if (modelo.getValueAt(linha, 0) != null){
            String[] detalhes = new String[7];
            detalhes[0] = modelo.getValueAt(linha, 0).toString();
            detalhes[1] = modelo.getValueAt(linha, 1).toString();
            detalhes[2] = modelo.getValueAt(linha, 2).toString();
            detalhes[3] = modelo.getValueAt(linha, 3).toString();
            detalhes[4] = modelo.getValueAt(linha, 4).toString();
            detalhes[5] = modelo.getValueAt(linha, 5).toString();
            detalhes[6] = modelo.getValueAt(linha, 6).toString();
            TelaDetalhes telaDetalhes = new TelaDetalhes();
            telaDetalhes.setVisible(true);
            telaDetalhes.receberDetalhes(detalhes);
        }
        else{
            JOptionPane.showMessageDialog(null, "Atualize a lista primeiro");
        }
        
    }
    
    private void read(){
        
        ArrayList<Aluno> lista = alunoDao.readAll();
        DefaultTableModel modelo = (DefaultTableModel)tabelaAlunos.getModel();
        if (lista != null){
            modelo.setNumRows(0);
            for (Aluno a : lista) {
                modelo.addRow(new Object[]{a.getId(), a.getCpf(), a.getNome(), a.getDataNascimento(), a.getTelefone(), a.getEmail(), a.getEndereco()});
            }
        }
    }
    
    private String selecionarAluno(){
        DefaultTableModel modelo = (DefaultTableModel)tabelaAlunos.getModel();
        try{
            int linha = tabelaAlunos.getSelectedRow();
            String campo = modelo.getValueAt(linha, 0).toString();
            return campo;
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Certifique-se de escolher o aluno, Erro ao escolher aluno "+ e);
            return null;
        }
    }
    
    private void delete(String d){
        int alunoDeletado = Integer.valueOf(d);
        try{
            aluno.setId(alunoDeletado);
            
            alunoDao.delete(aluno);
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Erro ao salvar os dados: " + e.toString());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCreate;
    private javax.swing.JButton botaoDelete;
    private javax.swing.JButton botaoDetalhe;
    private javax.swing.JButton botaoExit;
    private javax.swing.JButton botaoRead;
    private javax.swing.JButton botaoUpdate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaAlunos;
    // End of variables declaration//GEN-END:variables
}
